// WorkMode — Strategy 패턴으로 Operator(대화)와 Worker(작업)의 차이를 캡슐화.
//
// 공유: Rig<M>.process() → Agent.reply()
// 차이: 세션 관리 (영속 vs 작업당)

use goose::agents::SessionConfig;

/// A unit of work passed to an agent.
///
/// Created via [`WorkInput::chat`] for conversational input or
/// [`WorkInput::task`] for board work items.
pub struct WorkInput {
    pub text: String,
    pub work_id: Option<i64>,
    /// 미리 생성된 Goose 세션 ID. 설정 시 WorkMode.session_for()보다 우선.
    pub session_id: Option<String>,
}

impl WorkInput {
    /// Create a chat input (no associated work item).
    ///
    /// ```
    /// use opengoose_rig::work_mode::WorkInput;
    ///
    /// let input = WorkInput::chat("Hello, agent!");
    /// assert_eq!(input.text, "Hello, agent!");
    /// assert!(input.work_id.is_none());
    /// assert!(input.session_id.is_none());
    /// ```
    pub fn chat(text: impl Into<String>) -> Self {
        Self {
            text: text.into(),
            work_id: None,
            session_id: None,
        }
    }

    /// Create a task input tied to a board work item.
    ///
    /// ```
    /// use opengoose_rig::work_mode::WorkInput;
    ///
    /// let input = WorkInput::task("Fix the auth bug", 42);
    /// assert_eq!(input.text, "Fix the auth bug");
    /// assert_eq!(input.work_id, Some(42));
    /// ```
    pub fn task(text: impl Into<String>, work_id: i64) -> Self {
        Self {
            text: text.into(),
            work_id: Some(work_id),
            session_id: None,
        }
    }

    /// Attach a pre-created session ID. When set, this takes priority
    /// over the ID generated by [`WorkMode::session_for`].
    ///
    /// ```
    /// use opengoose_rig::work_mode::WorkInput;
    ///
    /// let input = WorkInput::chat("hi")
    ///     .with_session_id("my-session-123".into());
    /// assert_eq!(input.session_id.as_deref(), Some("my-session-123"));
    /// ```
    pub fn with_session_id(mut self, id: String) -> Self {
        self.session_id = Some(id);
        self
    }
}

/// Canonical session ID for task-mode work items.
///
/// ```
/// use opengoose_rig::work_mode::task_session_id;
///
/// assert_eq!(task_session_id(42), "task-42");
/// ```
pub fn task_session_id(id: i64) -> String {
    format!("task-{id}")
}

/// Canonical session ID for evolver-mode stamps.
///
/// ```
/// use opengoose_rig::work_mode::evolve_session_id;
///
/// assert_eq!(evolve_session_id(10), "evolve-10");
/// ```
pub fn evolve_session_id(id: i64) -> String {
    format!("evolve-{id}")
}

/// Strategy trait: encapsulates session management.
///
/// ChatMode: 영속 세션 → prompt cache 보장.
/// TaskMode: 작업당 세션 → 대화 캐시 오염 방지.
///
/// # Examples
///
/// ```
/// use opengoose_rig::work_mode::{TaskMode, WorkMode, WorkInput};
///
/// let input = WorkInput::task("implement feature X", 42);
/// let session_id = TaskMode.session_for(&input);
/// assert_eq!(session_id, "task-42");
/// ```
pub trait WorkMode: Send + Sync {
    /// 이 입력에 사용할 Goose 세션 ID.
    fn session_for(&self, input: &WorkInput) -> String;

    /// SessionConfig 생성 (편의 메서드).
    fn session_config(&self, input: &WorkInput) -> SessionConfig {
        SessionConfig {
            id: self.session_for(input),
            schedule_id: None,
            max_turns: None,
            retry_config: None,
        }
    }
}

/// Persistent session mode for Operator rigs.
///
/// The same `session_id` is reused across all inputs, guaranteeing
/// prompt cache hits.
///
/// ```
/// use opengoose_rig::work_mode::{ChatMode, WorkMode, WorkInput};
///
/// let mode = ChatMode::new("persistent-session");
/// let a = mode.session_for(&WorkInput::chat("hello"));
/// let b = mode.session_for(&WorkInput::chat("world"));
/// assert_eq!(a, b); // always the same session
/// ```
pub struct ChatMode {
    session_id: String,
}

impl ChatMode {
    pub fn new(session_id: impl Into<String>) -> Self {
        Self {
            session_id: session_id.into(),
        }
    }
}

impl WorkMode for ChatMode {
    fn session_for(&self, _input: &WorkInput) -> String {
        self.session_id.clone()
    }
}

/// Per-task session mode for Worker rigs.
///
/// Each work item gets its own session ID, preventing cache pollution.
///
/// ```
/// use opengoose_rig::work_mode::{TaskMode, WorkMode, WorkInput};
///
/// let mode = TaskMode;
/// let a = mode.session_for(&WorkInput::task("fix auth", 1));
/// let b = mode.session_for(&WorkInput::task("add tests", 2));
/// assert_eq!(a, "task-1");
/// assert_eq!(b, "task-2");
/// assert_ne!(a, b); // different sessions per task
/// ```
pub struct TaskMode;

impl WorkMode for TaskMode {
    fn session_for(&self, input: &WorkInput) -> String {
        // 미리 생성된 세션 ID가 있으면 우선 사용
        if let Some(id) = &input.session_id {
            return id.clone();
        }
        match input.work_id {
            Some(id) => task_session_id(id),
            None => format!(
                "task-{}",
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_millis()
            ),
        }
    }
}

/// Per-analysis session mode for Evolver rigs.
///
/// ```
/// use opengoose_rig::work_mode::{EvolveMode, WorkMode, WorkInput};
///
/// let mode = EvolveMode;
/// let id = mode.session_for(&WorkInput::task("analyze stamp", 5));
/// assert_eq!(id, "evolve-5");
/// ```
pub struct EvolveMode;

impl WorkMode for EvolveMode {
    fn session_for(&self, input: &WorkInput) -> String {
        if let Some(id) = &input.session_id {
            return id.clone();
        }
        match input.work_id {
            Some(id) => evolve_session_id(id),
            None => format!(
                "evolve-{}",
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_millis()
            ),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn chat_mode_returns_same_session() {
        let mode = ChatMode::new("session-abc");
        let a = mode.session_for(&WorkInput::chat("hello"));
        let b = mode.session_for(&WorkInput::chat("world"));
        assert_eq!(a, b);
        assert_eq!(a, "session-abc");
    }

    #[test]
    fn task_mode_returns_unique_sessions() {
        let mode = TaskMode;
        let a = mode.session_for(&WorkInput::task("fix auth", 1));
        let b = mode.session_for(&WorkInput::task("add tests", 2));
        assert_eq!(a, "task-1");
        assert_eq!(b, "task-2");
        assert_ne!(a, b);
    }

    #[test]
    fn evolve_mode_returns_stamp_based_session() {
        let mode = EvolveMode;
        let a = mode.session_for(&WorkInput::task("analyze stamp", 5));
        assert_eq!(a, "evolve-5");
    }

    #[test]
    fn session_config_uses_session_for() {
        let mode = ChatMode::new("my-session");
        let config = mode.session_config(&WorkInput::chat("hi"));
        assert_eq!(config.id, "my-session");
    }

    #[test]
    fn task_mode_uses_presupplied_session_id() {
        let mode = TaskMode;
        let input = WorkInput::task("do something", 42).with_session_id("pre-session-xyz".into());
        let id = mode.session_for(&input);
        assert_eq!(id, "pre-session-xyz");
    }

    #[test]
    fn task_mode_generates_timestamp_session_when_no_work_id() {
        let mode = TaskMode;
        let input = WorkInput::chat("no work_id here");
        let id = mode.session_for(&input);
        assert!(
            id.starts_with("task-"),
            "expected 'task-' prefix, got: {id}"
        );
    }

    #[test]
    fn evolve_mode_generates_timestamp_session_when_no_work_id() {
        let mode = EvolveMode;
        let input = WorkInput::chat("no work_id");
        let id = mode.session_for(&input);
        assert!(
            id.starts_with("evolve-"),
            "expected 'evolve-' prefix, got: {id}"
        );
    }

    #[test]
    fn work_input_with_session_id_sets_field() {
        let input = WorkInput::chat("hello").with_session_id("my-sid".into());
        assert_eq!(input.session_id.as_deref(), Some("my-sid"));
    }

    #[test]
    fn evolve_mode_uses_presupplied_session_id() {
        let mode = EvolveMode;
        let input = WorkInput::chat("x").with_session_id("pre-evolve".into());
        assert_eq!(mode.session_for(&input), "pre-evolve");
    }

    #[test]
    fn chat_mode_ignores_presupplied_session_id() {
        let mode = ChatMode::new("persistent");
        let input = WorkInput::chat("hi").with_session_id("override-attempt".into());
        assert_eq!(mode.session_for(&input), "persistent");
    }

    #[test]
    fn work_input_chat_defaults() {
        let input = WorkInput::chat("hello");
        assert_eq!(input.text, "hello");
        assert!(input.work_id.is_none());
        assert!(input.session_id.is_none());
    }

    #[test]
    fn work_input_task_defaults() {
        let input = WorkInput::task("do it", 99);
        assert_eq!(input.text, "do it");
        assert_eq!(input.work_id, Some(99));
        assert!(input.session_id.is_none());
    }

    #[test]
    fn task_session_id_format() {
        assert_eq!(task_session_id(0), "task-0");
        assert_eq!(task_session_id(123), "task-123");
    }

    #[test]
    fn evolve_session_id_format() {
        assert_eq!(evolve_session_id(0), "evolve-0");
        assert_eq!(evolve_session_id(777), "evolve-777");
    }

    #[test]
    fn work_input_empty_text() {
        let input = WorkInput::chat("");
        assert_eq!(input.text, "");
    }

    #[test]
    fn evolve_mode_session_config_delegates() {
        let mode = EvolveMode;
        let input = WorkInput::task("analyze", 10);
        let config = mode.session_config(&input);
        assert_eq!(config.id, "evolve-10");
        assert!(config.schedule_id.is_none());
        assert!(config.max_turns.is_none());
        assert!(config.retry_config.is_none());
    }
}
